import { getSupabaseAdmin, q } from "@/lib/data";
import { loadUserAssetSummaries } from "@/lib/assets";
import { formatCompactNumber, formatDateTime, formatUsd, shortId } from "@/lib/format";
import { Empty, ErrorNote, PageHeader, Pill, Section, TableWrap, Td, Th } from "@/components/ui";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
const PAGE_SIZE = 30;
const DAY = 24 * 3600 * 1000;
type UserRow = { id: string; username: string | null; email: string | null; created_at: string | null; last_activity_at: string | null };

export default async function UsersPage({ searchParams }: { searchParams: { q?: string; page?: string } }) {
  const db = getSupabaseAdmin(); const page = Math.max(1, Number(searchParams.page) || 1); const from = (page - 1) * PAGE_SIZE; const to = from + PAGE_SIZE - 1; const term = (searchParams.q || "").trim();
  let query = db.from("admin_users_overview").select("id, username, email, created_at, last_activity_at", { count: "exact" }).order("last_activity_at", { ascending: false }).range(from, to);
  if (term) query = query.or(`username.ilike.%${term}%,email.ilike.%${term}%`);
  const [usersRes, assets, balanceRows] = await Promise.all([query, loadUserAssetSummaries(), q<any>(db.from("user_balances").select("user_id, available_balance, staking_balance, pending_balance"))]);
  const rows = (usersRes.data || []) as UserRow[]; const total = usersRes.count ?? rows.length; const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  const usersWithBalance = new Set<string>(); for (const row of balanceRows.rows) if (Number(row.available_balance || 0) + Number(row.staking_balance || 0) + Number(row.pending_balance || 0) > 0) usersWithBalance.add(String(row.user_id));
  const now = Date.now(); const since7d = new Date(now - 7 * DAY).toISOString(); const active7d = rows.filter((u) => u.last_activity_at && u.last_activity_at >= since7d).length; const new7d = rows.filter((u) => u.created_at && u.created_at >= since7d).length;
  function pageHref(p: number) { const params = new URLSearchParams(); if (term) params.set("q", term); if (p > 1) params.set("page", String(p)); const qs = params.toString(); return `/dashboard/users${qs ? `?${qs}` : ""}`; }
  return <div><PageHeader title="Utilisateurs" subtitle="Comptes, activité et soldes par actif de la plateforme." updatedAt={formatDateTime(new Date())} /><ErrorNote text={usersRes.error || assets.error ? `Certaines données n'ont pas pu être lues : ${[usersRes.error, assets.error].filter(Boolean).join(" · ")}` : null} /><div className="wk-strip"><StatCard label="Total comptes" value={formatCompactNumber(total)} sub="Tous les comptes" /><StatCard label="Actifs 7j" value={formatCompactNumber(active7d)} sub="Dernière activité récente" /><StatCard label="Nouveaux 7j" value={formatCompactNumber(new7d)} sub="Comptes créés récemment" /><StatCard label="Avec un solde" value={formatCompactNumber(usersWithBalance.size)} sub={`${assets.rows.length} actif(s) suivis`} /></div><Section title="Recherche"><form method="get" style={{ display: "flex", gap: 12, flexWrap: "wrap", alignItems: "flex-end" }}><div style={{ flex: "1 1 260px" }}><label className="wk-label" htmlFor="q">Recherche</label><input id="q" name="q" type="text" defaultValue={term} placeholder="Nom d'utilisateur ou email" className="wk-input" /></div><button type="submit" className="wk-btn">Rechercher</button>{term && <a href="/dashboard/users" className="wk-link">Réinitialiser</a>}</form></Section><Section title="Comptes" hint={`${total} résultat(s) trouvé(s).`}>{rows.length === 0 ? <Empty text="Aucun utilisateur trouvé pour ces filtres." /> : <><TableWrap><thead><tr><Th>Utilisateur</Th><Th>Email</Th><Th>Créé le</Th><Th>Dernière activité</Th><Th>Solde</Th><Th>Statut</Th></tr></thead><tbody>{rows.map((user) => { const recent = !!user.last_activity_at && new Date(user.last_activity_at).getTime() > now - 30 * DAY; return <tr key={user.id}><Td label="Utilisateur"><a className="wk-link" href={`/dashboard/users/${user.id}`}><div className="wk-asset">{user.username || "Sans pseudo"}</div><div className="wk-asset-sub">{shortId(user.id)}</div></a></Td><Td label="Email"><span className="wk-asset-sub">{user.email || "—"}</span></Td><Td label="Créé le">{user.created_at ? formatDateTime(new Date(user.created_at)) : "—"}</Td><Td label="Dernière activité">{user.last_activity_at ? formatDateTime(new Date(user.last_activity_at)) : "—"}</Td><Td label="Solde">{usersWithBalance.has(user.id) ? <Pill tone="info">Actif</Pill> : <span className="wk-asset-sub">Aucun actif</span>}</Td><Td label="Statut">{recent ? <Pill tone="ok">Actif</Pill> : <Pill tone="warn">Peu actif</Pill>}</Td></tr>; })}</tbody></TableWrap>{totalPages > 1 && <div style={{ display: "flex", justifyContent: "space-between", marginTop: 16 }}><span className="wk-asset-sub">Page {page} sur {totalPages}</span><div style={{ display: "flex", gap: 10 }}>{page > 1 && <a href={pageHref(page - 1)} className="wk-link">← Précédent</a>}{page < totalPages && <a href={pageHref(page + 1)} className="wk-link">Suivant →</a>}</div></div>}</>}</Section></div>;
}
function StatCard({ label, value, sub }: { label: string; value: string; sub: string }) { return <div className="wk-strip-item"><div className="wk-strip-label">{label}</div><div className="wk-strip-value">{value}</div><div className="wk-strip-sub">{sub}</div></div>; }
