-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text NOT NULL UNIQUE,
  email text UNIQUE,
  phone text,
  avatar_url text,
  country_code text DEFAULT 'CM'::text,
  is_verified boolean DEFAULT false,
  referral_code text DEFAULT referral.generate_referral_code() UNIQUE,
  referred_by uuid,
  referral_level integer DEFAULT 1,
  total_referrals integer DEFAULT 0,
  total_games_played integer DEFAULT 0,
  user_level integer DEFAULT 1,
  experience_points integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email_confirmed boolean NOT NULL DEFAULT false,
  profile_completed boolean NOT NULL DEFAULT false,
  display_currency text NOT NULL DEFAULT 'USD'::text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT fk_users_level FOREIGN KEY (user_level) REFERENCES public.user_levels_config(level),
  CONSTRAINT users_referred_by_fkey FOREIGN KEY (referred_by) REFERENCES public.users(id)
);
CREATE TABLE public.wheel_segments (
  id integer NOT NULL DEFAULT nextval('wheel_segments_id_seq'::regclass),
  label text NOT NULL,
  reward_type text NOT NULL,
  asset_symbol text,
  reward_amount numeric DEFAULT 0,
  multiplier_value numeric DEFAULT 1,
  probability numeric NOT NULL CHECK (probability > 0::numeric AND probability <= 1::numeric),
  color text DEFAULT '#3B82F6'::text,
  icon text,
  min_user_level integer DEFAULT 1,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  free_spins_reward integer DEFAULT 0,
  is_jackpot boolean DEFAULT false,
  display_order integer DEFAULT 0,
  CONSTRAINT wheel_segments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_wheel_segments_asset FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol)
);
CREATE TABLE public.wheel_spins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  segment_id integer,
  bet_amount numeric DEFAULT 0,
  bet_asset text,
  reward_amount numeric DEFAULT 0,
  reward_asset text,
  final_reward_amount numeric DEFAULT 0,
  active_multiplier numeric DEFAULT 1,
  multiplier_expires_at timestamp with time zone,
  client_seed text,
  server_seed text,
  nonce integer,
  spin_hash text,
  spin_result jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wheel_spins_pkey PRIMARY KEY (id),
  CONSTRAINT wheel_spins_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT wheel_spins_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES public.wheel_segments(id)
);
CREATE TABLE public.user_levels_config (
  level integer NOT NULL,
  name text NOT NULL,
  required_xp integer NOT NULL,
  benefits jsonb DEFAULT '{}'::jsonb,
  level_up_reward jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_levels_config_pkey PRIMARY KEY (level)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  asset_symbol text NOT NULL,
  address text NOT NULL,
  derivation_index integer NOT NULL,
  network text NOT NULL,
  is_active boolean DEFAULT true,
  last_balance_check timestamp with time zone DEFAULT now(),
  cached_balance numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT user_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_user_addresses_asset FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol)
);
CREATE TABLE public.user_balances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  asset_symbol text NOT NULL,
  available_balance numeric DEFAULT 0 CHECK (available_balance IS NULL OR available_balance >= 0::numeric),
  staking_balance numeric DEFAULT 0 CHECK (staking_balance IS NULL OR staking_balance >= 0::numeric),
  pending_balance numeric DEFAULT 0 CHECK (pending_balance IS NULL OR pending_balance >= 0::numeric),
  total_deposited numeric DEFAULT 0,
  total_withdrawn numeric DEFAULT 0,
  total_earned_staking numeric DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_balances_pkey PRIMARY KEY (id),
  CONSTRAINT user_balances_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_user_balances_asset FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol)
);
CREATE TABLE public.supported_assets (
  id integer NOT NULL DEFAULT nextval('supported_assets_id_seq'::regclass),
  symbol text NOT NULL UNIQUE,
  name text NOT NULL,
  network text NOT NULL,
  contract_address text,
  decimals integer DEFAULT 18,
  icon_url text,
  is_native boolean DEFAULT false,
  derivation_path text,
  min_deposit numeric DEFAULT 0,
  min_withdraw numeric DEFAULT 0,
  withdraw_fee numeric DEFAULT 0,
  transfer_fee_percentage numeric DEFAULT 0.5,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  min_p2p_transfer numeric DEFAULT 0,
  max_p2p_transfer numeric DEFAULT 1000000,
  can_be_p2p boolean DEFAULT true,
  max_withdraw numeric DEFAULT 100,
  can_be_withdrawn boolean DEFAULT true,
  can_be_swapped boolean DEFAULT true,
  coingecko_id text,
  swap_fee_percentage numeric DEFAULT 0.5,
  max_deposit numeric,
  min_sweep numeric NOT NULL DEFAULT 0,
  withdraw_fee_percentage numeric,
  ledger_symbol text NOT NULL,
  can_be_deposited boolean NOT NULL DEFAULT true,
  CONSTRAINT supported_assets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['deposit'::text, 'withdrawal'::text, 'transfer'::text, 'p2p_transfer'::text, 'swap_debit'::text, 'swap_credit'::text, 'staking'::text, 'staking_reward'::text, 'staking_lock'::text, 'unstake_completed'::text, 'game_bet'::text, 'game_win'::text, 'referral_bonus'::text, 'cashback'::text, 'refund'::text, 'commission'::text, 'dividend_payment'::text, 'wakati_purchase'::text, 'asset_conversion'::text, 'lending_reward'::text, 'internal_transfer'::text, 'balance_adjustment'::text, 'fee'::text, 'unstake_request'::text, 'unstake'::text, 'instant_unstake'::text, 'buy_wakati'::text, 'stake'::text, 'airtime_purchase'::text, 'burn'::text, 'admin_reclaim'::text, 'loan_collateral_lock'::text, 'loan_borrowed'::text, 'loan_repaid'::text, 'loan_collateral_release'::text, 'loan_liquidated'::text, 'score_loan_borrowed'::text, 'score_loan_fee'::text, 'score_loan_repaid'::text, 'score_loan_defaulted'::text, 'score_loan_debt_recovered'::text])),
  asset_symbol text NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  fee numeric DEFAULT 0 CHECK (fee >= 0::numeric),
  net_amount numeric,
  status text DEFAULT 'pending'::text,
  reference_id uuid,
  counterparty_id uuid,
  parent_transaction_id uuid,
  tx_hash text,
  block_number bigint,
  confirmations integer DEFAULT 0,
  gas_fee numeric DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  device_info jsonb,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  network text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_parent_transaction_id_fkey FOREIGN KEY (parent_transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT fk_transactions_asset FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol),
  CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT transactions_counterparty_id_fkey FOREIGN KEY (counterparty_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_kyc (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  verification_level text NOT NULL DEFAULT 'none'::text CHECK (verification_level = ANY (ARRAY['none'::text, 'basic'::text, 'intermediate'::text, 'advanced'::text])),
  id_document_type text,
  id_document_number text,
  id_document_front_url text,
  id_document_back_url text,
  selfie_url text,
  verification_status text NOT NULL DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'expired'::text])),
  verified_at timestamp with time zone,
  verified_by uuid,
  rejection_reason text,
  expiry_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_kyc_pkey PRIMARY KEY (id),
  CONSTRAINT user_kyc_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id),
  CONSTRAINT user_kyc_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_transaction_limits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  daily_withdraw_limit numeric NOT NULL DEFAULT 10000,
  daily_withdraw_used numeric NOT NULL DEFAULT 0 CHECK (daily_withdraw_used >= 0::numeric),
  daily_deposit_limit numeric NOT NULL DEFAULT 10000,
  daily_deposit_used numeric NOT NULL DEFAULT 0,
  monthly_withdraw_limit numeric NOT NULL DEFAULT 30000,
  monthly_withdraw_used numeric NOT NULL DEFAULT 0 CHECK (monthly_withdraw_used >= 0::numeric),
  last_daily_reset date NOT NULL DEFAULT CURRENT_DATE,
  last_monthly_reset date NOT NULL DEFAULT date_trunc('month'::text, (CURRENT_DATE)::timestamp with time zone),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_transaction_limits_pkey PRIMARY KEY (id),
  CONSTRAINT user_transaction_limits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.auth_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action text NOT NULL,
  details jsonb DEFAULT '{}'::jsonb,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT auth_logs_pkey PRIMARY KEY (id),
  CONSTRAINT auth_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_active_multipliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  multiplier_value numeric DEFAULT 1.0 CHECK (multiplier_value >= 1.0),
  spins_remaining integer DEFAULT 0 CHECK (spins_remaining >= 0),
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_active_multipliers_pkey PRIMARY KEY (id),
  CONSTRAINT user_active_multipliers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.staking_pools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  asset_symbol text NOT NULL,
  base_apy numeric NOT NULL CHECK (base_apy >= 0::numeric),
  min_stake numeric NOT NULL DEFAULT 0 CHECK (min_stake >= 0::numeric),
  total_staked numeric NOT NULL DEFAULT 0 CHECK (total_staked >= 0::numeric),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  description text,
  total_rewards_distributed numeric DEFAULT 0,
  staking_type text NOT NULL DEFAULT 'flexible'::text CHECK (staking_type = ANY (ARRAY['flexible'::text, 'locked'::text])),
  lock_period_days integer NOT NULL DEFAULT 0,
  max_stake numeric,
  instant_unstake_fee_percent numeric,
  sort_order integer NOT NULL DEFAULT 100,
  instant_unstake_enabled boolean NOT NULL DEFAULT true,
  max_pool_capacity numeric,
  CONSTRAINT staking_pools_pkey PRIMARY KEY (id),
  CONSTRAINT staking_pools_asset_symbol_fkey FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol)
);
CREATE TABLE public.user_stakes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  pool_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'unstaking'::text, 'unstaked'::text])),
  pending_rewards numeric NOT NULL DEFAULT 0 CHECK (pending_rewards >= 0::numeric),
  rewards_earned numeric NOT NULL DEFAULT 0 CHECK (rewards_earned >= 0::numeric),
  staked_at timestamp with time zone NOT NULL DEFAULT now(),
  last_reward_calculation timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  initial_apy numeric DEFAULT 0,
  unlock_at timestamp with time zone,
  CONSTRAINT user_stakes_pkey PRIMARY KEY (id),
  CONSTRAINT user_stakes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_stakes_pool_id_fkey FOREIGN KEY (pool_id) REFERENCES public.staking_pools(id)
);
CREATE TABLE public.asset_prices (
  asset_symbol text NOT NULL,
  price_usd numeric NOT NULL DEFAULT 0 CHECK (price_usd >= 0::numeric),
  change_24h numeric NOT NULL DEFAULT 0,
  market_cap numeric NOT NULL DEFAULT 0 CHECK (market_cap >= 0::numeric),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT asset_prices_pkey PRIMARY KEY (asset_symbol)
);
CREATE TABLE public.supported_assets_metrics (
  asset_symbol text NOT NULL,
  total_deposited numeric NOT NULL DEFAULT 0 CHECK (total_deposited >= 0::numeric),
  total_deposit_count integer NOT NULL DEFAULT 0 CHECK (total_deposit_count >= 0),
  total_withdrawn numeric NOT NULL DEFAULT 0 CHECK (total_withdrawn >= 0::numeric),
  total_withdrawal_count integer NOT NULL DEFAULT 0 CHECK (total_withdrawal_count >= 0),
  pending_withdrawals numeric NOT NULL DEFAULT 0 CHECK (pending_withdrawals >= 0::numeric),
  total_staked numeric NOT NULL DEFAULT 0 CHECK (total_staked >= 0::numeric),
  total_swap_volume numeric NOT NULL DEFAULT 0 CHECK (total_swap_volume >= 0::numeric),
  total_p2p_volume numeric NOT NULL DEFAULT 0 CHECK (total_p2p_volume >= 0::numeric),
  total_fees_collected numeric NOT NULL DEFAULT 0 CHECK (total_fees_collected >= 0::numeric),
  total_user_balance numeric NOT NULL DEFAULT 0 CHECK (total_user_balance >= 0::numeric),
  net_position numeric NOT NULL DEFAULT 0,
  should_be_in_custody numeric NOT NULL DEFAULT 0,
  last_updated timestamp with time zone NOT NULL DEFAULT now(),
  total_swap_fees_collected numeric NOT NULL DEFAULT 0 CHECK (total_swap_fees_collected >= 0::numeric),
  total_p2p_fees_collected numeric NOT NULL DEFAULT 0 CHECK (total_p2p_fees_collected >= 0::numeric),
  total_withdraw_fees_collected numeric NOT NULL DEFAULT 0 CHECK (total_withdraw_fees_collected >= 0::numeric),
  total_burned numeric NOT NULL DEFAULT 0 CHECK (total_burned >= 0::numeric),
  CONSTRAINT supported_assets_metrics_pkey PRIMARY KEY (asset_symbol),
  CONSTRAINT supported_assets_metrics_asset_symbol_fkey FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol)
);
CREATE TABLE public.platform_fees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_symbol text NOT NULL,
  amount numeric NOT NULL,
  fee_type text NOT NULL,
  source_user_id uuid,
  source_transaction_id uuid,
  collected_at timestamp with time zone DEFAULT now(),
  is_test boolean NOT NULL DEFAULT false,
  CONSTRAINT platform_fees_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_dashboard_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  snapshot_date date NOT NULL DEFAULT CURRENT_DATE UNIQUE,
  total_users integer NOT NULL DEFAULT 0,
  new_users_today integer NOT NULL DEFAULT 0,
  total_active_stakes integer NOT NULL DEFAULT 0,
  total_staked_usd numeric NOT NULL DEFAULT 0,
  total_rewards_distributed_usd numeric NOT NULL DEFAULT 0,
  total_fees_collected_usd numeric NOT NULL DEFAULT 0,
  fees_by_type jsonb NOT NULL DEFAULT '{}'::jsonb,
  fees_by_asset jsonb NOT NULL DEFAULT '{}'::jsonb,
  total_swap_volume_usd numeric NOT NULL DEFAULT 0,
  total_p2p_volume_usd numeric NOT NULL DEFAULT 0,
  total_deposits_usd numeric NOT NULL DEFAULT 0,
  total_withdrawals_usd numeric NOT NULL DEFAULT 0,
  active_pools integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_dashboard_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.asset_prices_history (
  id bigint NOT NULL DEFAULT nextval('asset_prices_history_id_seq'::regclass),
  asset_symbol text NOT NULL,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  price_usd numeric NOT NULL DEFAULT 0 CHECK (price_usd >= 0::numeric),
  price_open_24h numeric,
  price_high_24h numeric,
  price_low_24h numeric,
  change_24h_pct numeric,
  change_24h_usd numeric,
  volume_24h_usd numeric,
  market_cap_usd numeric,
  market_cap_rank integer,
  circulating_supply numeric,
  total_supply numeric,
  source text NOT NULL DEFAULT 'coingecko'::text,
  coingecko_id text,
  CONSTRAINT asset_prices_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.wheel_config (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  free_spins_daily integer NOT NULL DEFAULT 3,
  paid_spin_cost_amount numeric NOT NULL DEFAULT 100,
  jackpot_contribution_pct numeric NOT NULL DEFAULT 5,
  jackpot_current_amount numeric NOT NULL DEFAULT 0,
  jackpot_asset_symbol text NOT NULL DEFAULT 'WAKATI'::text,
  streak_bonus_free_spins integer NOT NULL DEFAULT 1,
  streak_bonus_interval integer NOT NULL DEFAULT 7,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  paid_spin_cost_asset text NOT NULL DEFAULT 'WAKATI'::text,
  messages jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT wheel_config_pkey PRIMARY KEY (id),
  CONSTRAINT wheel_config_paid_spin_cost_asset_fkey FOREIGN KEY (paid_spin_cost_asset) REFERENCES public.supported_assets(symbol)
);
CREATE TABLE public.user_wheel_stats (
  user_id uuid NOT NULL,
  free_spins_remaining integer NOT NULL DEFAULT 0,
  free_spins_reset_at timestamp with time zone NOT NULL DEFAULT now(),
  current_streak integer NOT NULL DEFAULT 0,
  longest_streak integer NOT NULL DEFAULT 0,
  last_spin_date date,
  total_spins integer NOT NULL DEFAULT 0,
  total_free_spins_used integer NOT NULL DEFAULT 0,
  total_paid_spins_used integer NOT NULL DEFAULT 0,
  total_wakati_spent numeric NOT NULL DEFAULT 0,
  total_winnings_usd numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_wheel_stats_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_wheel_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.staking_config (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  apr numeric NOT NULL DEFAULT 12.00,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by text,
  CONSTRAINT staking_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.prediction_config (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  is_active boolean NOT NULL DEFAULT true,
  asset_symbol text NOT NULL DEFAULT 'BTC'::text,
  asset_name text NOT NULL DEFAULT 'Bitcoin'::text,
  bet_amount numeric NOT NULL DEFAULT 100,
  bet_mode text NOT NULL DEFAULT 'fixed'::text CHECK (bet_mode = ANY (ARRAY['fixed'::text, 'range'::text])),
  bet_min numeric NOT NULL DEFAULT 50,
  bet_max numeric NOT NULL DEFAULT 500,
  win_multiplier numeric NOT NULL DEFAULT 1.50,
  duration_seconds integer NOT NULL DEFAULT 300,
  max_bets_per_day integer NOT NULL DEFAULT 20,
  cooldown_seconds integer NOT NULL DEFAULT 30,
  currency_symbol text NOT NULL DEFAULT 'WAKATI'::text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by text,
  CONSTRAINT prediction_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.prediction_bets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['UP'::text, 'DOWN'::text])),
  bet_amount numeric NOT NULL,
  currency_symbol text NOT NULL DEFAULT 'WAKATI'::text,
  price_at_bet numeric NOT NULL,
  price_at_resolution numeric,
  bet_at timestamp with time zone NOT NULL DEFAULT now(),
  resolves_at timestamp with time zone NOT NULL,
  resolved_at timestamp with time zone,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'won'::text, 'lost'::text, 'cancelled'::text, 'expired'::text])),
  payout_amount numeric,
  profit_amount numeric,
  win_multiplier numeric NOT NULL DEFAULT 1.50,
  duration_seconds integer NOT NULL DEFAULT 300,
  asset_symbol text NOT NULL DEFAULT 'BTC'::text,
  is_win boolean DEFAULT (status = 'won'::text),
  CONSTRAINT prediction_bets_pkey PRIMARY KEY (id),
  CONSTRAINT prediction_bets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.prediction_user_stats (
  user_id uuid NOT NULL,
  total_bets integer NOT NULL DEFAULT 0,
  total_wins integer NOT NULL DEFAULT 0,
  total_losses integer NOT NULL DEFAULT 0,
  total_wagered numeric NOT NULL DEFAULT 0,
  total_won numeric NOT NULL DEFAULT 0,
  total_lost numeric NOT NULL DEFAULT 0,
  net_profit numeric NOT NULL DEFAULT 0,
  win_streak integer NOT NULL DEFAULT 0,
  best_win_streak integer NOT NULL DEFAULT 0,
  loss_streak integer NOT NULL DEFAULT 0,
  last_bet_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT prediction_user_stats_pkey PRIMARY KEY (user_id),
  CONSTRAINT prediction_user_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.prediction_leaderboard (
  id bigint NOT NULL DEFAULT nextval('prediction_leaderboard_id_seq'::regclass),
  user_id uuid NOT NULL,
  period text NOT NULL,
  rank integer,
  total_bets integer NOT NULL DEFAULT 0,
  total_wins integer NOT NULL DEFAULT 0,
  win_rate numeric,
  net_profit numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT prediction_leaderboard_pkey PRIMARY KEY (id),
  CONSTRAINT prediction_leaderboard_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.treasury_wallets (
  asset_symbol text NOT NULL,
  balance numeric NOT NULL DEFAULT 0 CHECK (balance >= 0::numeric),
  total_collected numeric NOT NULL DEFAULT 0 CHECK (total_collected >= 0::numeric),
  total_burned numeric NOT NULL DEFAULT 0 CHECK (total_burned >= 0::numeric),
  total_withdrawn numeric NOT NULL DEFAULT 0 CHECK (total_withdrawn >= 0::numeric),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT treasury_wallets_pkey PRIMARY KEY (asset_symbol),
  CONSTRAINT treasury_wallets_asset_symbol_fkey FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol)
);
CREATE TABLE public.treasury_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_symbol text NOT NULL,
  entry_type text NOT NULL CHECK (entry_type = ANY (ARRAY['fee_credit'::text, 'burn'::text, 'admin_withdrawal'::text, 'adjustment'::text, 'backfill'::text, 'payout_debit'::text, 'admin_reclaim'::text, 'loan_disbursement'::text, 'loan_repayment'::text, 'liquidation'::text, 'wakati_sale'::text])),
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  balance_before numeric NOT NULL,
  balance_after numeric NOT NULL,
  source_transaction_id uuid,
  source_fee_id uuid,
  performed_by uuid,
  reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT treasury_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT treasury_ledger_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.users(id),
  CONSTRAINT treasury_ledger_asset_symbol_fkey FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol),
  CONSTRAINT treasury_ledger_source_transaction_id_fkey FOREIGN KEY (source_transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT treasury_ledger_source_fee_id_fkey FOREIGN KEY (source_fee_id) REFERENCES public.platform_fees(id)
);
CREATE TABLE public.token_burns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_symbol text NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  reason text,
  burned_by uuid,
  tx_hash text,
  status text NOT NULL DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['completed'::text, 'pending_onchain'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  source text NOT NULL CHECK (source = ANY (ARRAY['treasury'::text, 'user'::text])),
  CONSTRAINT token_burns_pkey PRIMARY KEY (id),
  CONSTRAINT token_burns_asset_symbol_fkey FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol),
  CONSTRAINT token_burns_burned_by_fkey FOREIGN KEY (burned_by) REFERENCES public.users(id)
);
CREATE TABLE public.loans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  collateral_asset text NOT NULL,
  collateral_amount numeric NOT NULL CHECK (collateral_amount > 0::numeric),
  borrow_asset text NOT NULL,
  principal_amount numeric NOT NULL CHECK (principal_amount >= 0::numeric),
  accrued_interest numeric NOT NULL DEFAULT 0 CHECK (accrued_interest >= 0::numeric),
  apr_rate_snapshot numeric NOT NULL,
  liquidation_ltv_snapshot numeric NOT NULL,
  fixed_fee_charged numeric NOT NULL DEFAULT 0,
  fixed_fee_asset text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'repaid'::text, 'liquidated'::text])),
  opened_at timestamp with time zone NOT NULL DEFAULT now(),
  last_interest_accrual_at timestamp with time zone NOT NULL DEFAULT now(),
  closed_at timestamp with time zone,
  CONSTRAINT loans_pkey PRIMARY KEY (id),
  CONSTRAINT loans_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.loan_liquidations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  loan_id uuid NOT NULL,
  collateral_to_treasury numeric NOT NULL,
  collateral_to_user numeric NOT NULL DEFAULT 0,
  debt_settled numeric NOT NULL,
  collateral_price_usd numeric NOT NULL,
  borrow_price_usd numeric NOT NULL,
  ltv_at_liquidation numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT loan_liquidations_pkey PRIMARY KEY (id),
  CONSTRAINT loan_liquidations_loan_id_fkey FOREIGN KEY (loan_id) REFERENCES public.loans(id)
);
CREATE TABLE public.lending_collateral_config (
  asset_symbol text NOT NULL,
  max_ltv_pct numeric NOT NULL CHECK (max_ltv_pct > 0::numeric AND max_ltv_pct < 100::numeric),
  liquidation_ltv_pct numeric NOT NULL CHECK (liquidation_ltv_pct > 0::numeric AND liquidation_ltv_pct < 100::numeric),
  liquidation_penalty_pct numeric NOT NULL DEFAULT 2 CHECK (liquidation_penalty_pct >= 0::numeric AND liquidation_penalty_pct < 50::numeric),
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  fixed_fee_amount numeric NOT NULL DEFAULT 0 CHECK (fixed_fee_amount >= 0::numeric),
  CONSTRAINT lending_collateral_config_pkey PRIMARY KEY (asset_symbol),
  CONSTRAINT lending_collateral_config_asset_symbol_fkey FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol)
);
CREATE TABLE public.lending_borrow_config (
  asset_symbol text NOT NULL,
  apr_rate_pct numeric NOT NULL CHECK (apr_rate_pct >= 0::numeric),
  min_borrow_amount numeric NOT NULL DEFAULT 0 CHECK (min_borrow_amount >= 0::numeric),
  max_borrow_amount numeric,
  max_total_borrowed numeric,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lending_borrow_config_pkey PRIMARY KEY (asset_symbol),
  CONSTRAINT lending_borrow_config_asset_symbol_fkey FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol)
);
CREATE TABLE public.score_action_config (
  action_type text NOT NULL,
  points_min numeric NOT NULL CHECK (points_min >= 0::numeric),
  points_max numeric NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT score_action_config_pkey PRIMARY KEY (action_type)
);
CREATE TABLE public.user_engagement_points (
  user_id uuid NOT NULL,
  total_points numeric NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_engagement_points_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_engagement_points_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.score_credit_config (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  conversion_rate_base_pct numeric NOT NULL DEFAULT 90 CHECK (conversion_rate_base_pct > 0::numeric AND conversion_rate_base_pct <= 100::numeric),
  conversion_rate_step_pct numeric NOT NULL DEFAULT 5 CHECK (conversion_rate_step_pct >= 0::numeric),
  conversion_rate_max_pct numeric NOT NULL DEFAULT 100 CHECK (conversion_rate_max_pct <= 100::numeric),
  fee_window_days integer NOT NULL DEFAULT 90 CHECK (fee_window_days > 0),
  min_fees_required_usd numeric NOT NULL DEFAULT 1 CHECK (min_fees_required_usd >= 0::numeric),
  min_account_age_days integer NOT NULL DEFAULT 7 CHECK (min_account_age_days >= 0),
  first_loan_cap_usd numeric NOT NULL DEFAULT 5 CHECK (first_loan_cap_usd > 0::numeric),
  max_absolute_cap_usd numeric NOT NULL DEFAULT 50 CHECK (max_absolute_cap_usd > 0::numeric),
  grace_period_hours integer NOT NULL DEFAULT 48 CHECK (grace_period_hours >= 0),
  loan_duration_days integer NOT NULL DEFAULT 30 CHECK (loan_duration_days > 0),
  default_fee_multiplier numeric NOT NULL DEFAULT 1.5 CHECK (default_fee_multiplier >= 1::numeric),
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  game_house_edge_weight_pct numeric NOT NULL DEFAULT 50 CHECK (game_house_edge_weight_pct >= 0::numeric AND game_house_edge_weight_pct <= 100::numeric),
  extension_fee_pct numeric NOT NULL DEFAULT 3 CHECK (extension_fee_pct >= 0::numeric AND extension_fee_pct <= 100::numeric),
  extension_apr_surcharge_pct numeric NOT NULL DEFAULT 5 CHECK (extension_apr_surcharge_pct >= 0::numeric),
  extension_days integer NOT NULL DEFAULT 15 CHECK (extension_days > 0),
  max_extensions_per_loan integer NOT NULL DEFAULT 2 CHECK (max_extensions_per_loan >= 0),
  cross_asset_repay_fee_pct numeric NOT NULL DEFAULT 1.5 CHECK (cross_asset_repay_fee_pct >= 0::numeric AND cross_asset_repay_fee_pct <= 100::numeric),
  CONSTRAINT score_credit_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.score_loan_asset_config (
  asset_symbol text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  apr_rate_pct numeric NOT NULL CHECK (apr_rate_pct >= 0::numeric),
  fixed_fee_amount numeric NOT NULL DEFAULT 0 CHECK (fixed_fee_amount >= 0::numeric),
  min_borrow_amount numeric NOT NULL CHECK (min_borrow_amount > 0::numeric),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT score_loan_asset_config_pkey PRIMARY KEY (asset_symbol),
  CONSTRAINT score_loan_asset_config_asset_symbol_fkey FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol)
);
CREATE TABLE public.user_score_credit_state (
  user_id uuid NOT NULL,
  conversion_rate_pct numeric NOT NULL DEFAULT 90,
  default_count integer NOT NULL DEFAULT 0,
  last_default_at timestamp with time zone,
  has_completed_first_loan boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_score_credit_state_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_score_credit_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.score_loans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  asset_symbol text NOT NULL,
  principal_amount numeric NOT NULL CHECK (principal_amount >= 0::numeric),
  accrued_interest numeric NOT NULL DEFAULT 0 CHECK (accrued_interest >= 0::numeric),
  apr_rate_snapshot numeric NOT NULL,
  fixed_fee_charged numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'repaid'::text, 'defaulted'::text])),
  opened_at timestamp with time zone NOT NULL DEFAULT now(),
  due_at timestamp with time zone NOT NULL,
  grace_until timestamp with time zone NOT NULL,
  closed_at timestamp with time zone,
  extensions_used integer NOT NULL DEFAULT 0,
  CONSTRAINT score_loans_pkey PRIMARY KEY (id),
  CONSTRAINT score_loans_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT score_loans_asset_symbol_fkey FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol)
);
CREATE TABLE public.wakati_reserve_state (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  reserve_usd numeric NOT NULL DEFAULT 0,
  profit_share_pct numeric NOT NULL DEFAULT 30,
  max_daily_change_pct numeric NOT NULL DEFAULT 5,
  price_floor_usd numeric NOT NULL DEFAULT 0.00057,
  is_active boolean NOT NULL DEFAULT true,
  last_computed_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wakati_reserve_state_pkey PRIMARY KEY (id)
);
CREATE TABLE public.wakati_price_history (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  computed_for_date date NOT NULL,
  net_profit_usd numeric NOT NULL,
  reserve_contribution_usd numeric NOT NULL,
  reserve_usd_after numeric NOT NULL,
  circulating_supply numeric NOT NULL,
  raw_price_usd numeric NOT NULL,
  final_price_usd numeric NOT NULL,
  was_capped boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  price_before_usd numeric NOT NULL,
  CONSTRAINT wakati_price_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.campay_config (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  sandbox_min_deposit numeric NOT NULL DEFAULT 25,
  sandbox_max_deposit numeric,
  production_min_deposit numeric NOT NULL DEFAULT 100,
  production_max_deposit numeric,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT campay_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_providers (
  code text NOT NULL,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_providers_pkey PRIMARY KEY (code)
);
CREATE TABLE public.payment_countries (
  iso_code text NOT NULL,
  name text NOT NULL,
  dial_code text NOT NULL,
  currency_code text NOT NULL,
  provider_code text NOT NULL,
  phone_digits_min integer NOT NULL DEFAULT 8,
  phone_digits_max integer NOT NULL DEFAULT 9,
  min_deposit numeric,
  max_deposit numeric,
  min_withdraw numeric,
  max_withdraw numeric,
  withdraw_fee numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 100,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  iso3_code text,
  provider_operator_code text,
  fallback_provider_code text,
  wallet_asset_symbol text,
  deposit_enabled boolean NOT NULL DEFAULT true,
  withdraw_enabled boolean NOT NULL DEFAULT true,
  withdraw_fee_percentage numeric,
  CONSTRAINT payment_countries_pkey PRIMARY KEY (iso_code),
  CONSTRAINT payment_countries_wallet_asset_symbol_fkey FOREIGN KEY (wallet_asset_symbol) REFERENCES public.supported_assets(symbol),
  CONSTRAINT payment_countries_provider_code_fkey FOREIGN KEY (provider_code) REFERENCES public.payment_providers(code),
  CONSTRAINT payment_countries_fallback_provider_code_fkey FOREIGN KEY (fallback_provider_code) REFERENCES public.payment_providers(code)
);
CREATE TABLE public.sweep_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_address_id uuid,
  asset_symbol text NOT NULL,
  network text NOT NULL,
  from_address text NOT NULL,
  to_address text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  tx_hash text,
  status text NOT NULL CHECK (status = ANY (ARRAY['would_sweep'::text, 'swept'::text, 'skipped'::text, 'error'::text, 'gas_topped_up'::text])),
  error_message text,
  dry_run boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sweep_log_pkey PRIMARY KEY (id),
  CONSTRAINT sweep_log_user_address_id_fkey FOREIGN KEY (user_address_id) REFERENCES public.user_addresses(id)
);
CREATE TABLE public.payment_error_messages (
  failure_code text NOT NULL,
  message_fr text NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_error_messages_pkey PRIMARY KEY (failure_code)
);
CREATE TABLE public.admin_audit_log (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  actor text NOT NULL,
  action text NOT NULL,
  summary text NOT NULL,
  target text,
  changes jsonb,
  status text NOT NULL DEFAULT 'success'::text CHECK (status = ANY (ARRAY['success'::text, 'error'::text])),
  error_message text,
  ip text,
  user_agent text,
  CONSTRAINT admin_audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pending_address_requests (
  user_id uuid NOT NULL,
  asset_symbol text NOT NULL,
  request_id bigint NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pending_address_requests_pkey PRIMARY KEY (user_id, asset_symbol)
);
CREATE TABLE public.user_performance_daily (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  asset_symbol text NOT NULL,
  performance_date date NOT NULL,
  opening_balance numeric NOT NULL DEFAULT 0,
  closing_balance numeric NOT NULL DEFAULT 0,
  deposits_amount numeric NOT NULL DEFAULT 0,
  deposits_count integer NOT NULL DEFAULT 0,
  withdrawals_amount numeric NOT NULL DEFAULT 0,
  withdrawals_count integer NOT NULL DEFAULT 0,
  rewards_amount numeric NOT NULL DEFAULT 0,
  fees_amount numeric NOT NULL DEFAULT 0,
  game_wins_amount numeric NOT NULL DEFAULT 0,
  game_losses_amount numeric NOT NULL DEFAULT 0,
  staking_rewards_amount numeric NOT NULL DEFAULT 0,
  transfers_in_amount numeric NOT NULL DEFAULT 0,
  transfers_out_amount numeric NOT NULL DEFAULT 0,
  swaps_in_amount numeric NOT NULL DEFAULT 0,
  swaps_out_amount numeric NOT NULL DEFAULT 0,
  loans_received_amount numeric NOT NULL DEFAULT 0,
  loans_repaid_amount numeric NOT NULL DEFAULT 0,
  net_cashflow numeric NOT NULL DEFAULT 0,
  net_variation numeric NOT NULL DEFAULT 0,
  price_usd numeric,
  closing_value_usd numeric,
  net_variation_usd numeric,
  transaction_count integer NOT NULL DEFAULT 0,
  successful_transaction_count integer NOT NULL DEFAULT 0,
  failed_transaction_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_performance_daily_pkey PRIMARY KEY (id),
  CONSTRAINT user_performance_daily_asset_symbol_fkey FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol),
  CONSTRAINT user_performance_daily_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_risk_flags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  flag_type text NOT NULL,
  severity text NOT NULL DEFAULT 'info'::text CHECK (severity = ANY (ARRAY['info'::text, 'low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'acknowledged'::text, 'resolved'::text, 'dismissed'::text])),
  title text NOT NULL,
  description text NOT NULL,
  asset_symbol text,
  score_impact integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  detected_at timestamp with time zone NOT NULL DEFAULT now(),
  acknowledged_at timestamp with time zone,
  resolved_at timestamp with time zone,
  acknowledged_by text,
  resolved_by text,
  resolution_note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  source_transaction_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  rule_version text NOT NULL DEFAULT 'v1'::text,
  CONSTRAINT user_risk_flags_pkey PRIMARY KEY (id),
  CONSTRAINT user_risk_flags_asset_symbol_fkey FOREIGN KEY (asset_symbol) REFERENCES public.supported_assets(symbol),
  CONSTRAINT user_risk_flags_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_risk_score_history (
  user_id uuid NOT NULL,
  score integer NOT NULL DEFAULT 0 CHECK (score >= 0 AND score <= 100),
  level text NOT NULL DEFAULT 'normal'::text CHECK (level = ANY (ARRAY['normal'::text, 'watch'::text, 'high'::text, 'critical'::text])),
  kyc_score integer NOT NULL DEFAULT 0,
  transaction_score integer NOT NULL DEFAULT 0,
  withdrawal_score integer NOT NULL DEFAULT 0,
  loan_score integer NOT NULL DEFAULT 0,
  behavior_score integer NOT NULL DEFAULT 0,
  reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
  calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  scoring_version text NOT NULL DEFAULT 'v1'::text,
  CONSTRAINT user_risk_score_history_pkey PRIMARY KEY (id),
  CONSTRAINT user_risk_scores_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
